"""add approvals.consumed_at

Revision ID: 579a1368be9e
Revises: c22d578ddc2b
Create Date: 2026-08-13 10:41:06.337268

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "579a1368be9e"
down_revision: str | Sequence[str] | None = "c22d578ddc2b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("approvals", sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_approvals_consumed_at"), "approvals", ["consumed_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_approvals_consumed_at"), table_name="approvals")
    op.drop_column("approvals", "consumed_at")
    # ### end Alembic commands ###
